# RootWidget holds the ScreenManager
<RootWidget>:
    ScreenManager:
        HomeScreen:
            name: "home"
        PantryScreen:
            name: "pantry"
        ListScreen:
            name: "list"

# HomeScreen layout
<HomeScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 10

        Label:
            text: "Welcome To Pantry Raiders!"
            font_size: 32

        Button:
            text: "Go to Your Pantry"
            size_hint: (1, 0.2)
            on_press: root.go_to_pantry()  # calls method on HomeScreen
        
        Button:
            text: "Go to Your Grocery List"
            size_hint: (1, 0.2)
            on_press: root.go_to_list()  # calls method on HomeScreen

# PantryScreen layout
<PantryScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 10

        Label:
            id: result_label         # accessed in Python via self.ids.result_label
            text: "Pantry Inventory"
            font_size: 28

        Button:
            text: "Press Me"
            size_hint: (1, 0.2)
            on_press: root.on_button_press()  # calls method on DetailsScreen

        Button:
            text: "Go Back"
            size_hint: (1, 0.2)
            on_press: root.go_back()

# ListScreen layout
<ListScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 10

        Label:
            id: result_label         # accessed in Python via self.ids.result_label
            text: "Grocery List"
            font_size: 28

        Button:
            text: "Press Me"
            size_hint: (1, 0.2)
            on_press: root.on_button_press()  # calls method on DetailsScreen

        Button:
            text: "Go Back"
            size_hint: (1, 0.2)
            on_press: root.go_back()